### PR TITLE
Fixes hydraulic convergence problems

### PR DESCRIPTION
**Pull request by LRossman**
These updates fix some hydraulic convergence problems encountered after an initial round of testing. Also, the custom hash table was replaced by the STL map, keeping HashTable as an interface class.

### CODE REVIEW

**Comment by samhatchett** [comment]
Great. Would you mind reverting afb8ac7740963f2eb68f2cabcf0bb58bf3d19e63 and making your suggestion to wrap the map implementation over on PR #5 - otherwise we will create conflicts with this PR once that one is merged.

**Comment by samhatchett** [comment]
Thanks! Based on our previous ad-hoc decision (and pending other better ideas on opinion sharing), we've got a 72-hour clock here. Put your votes in the Top Post 👆 and any comments below 👇 
- 👍 = +1 (thumb up)
- 😄= +0 (laugh)
- 😕 = -0 (confused)
- 👎 = -1 (thumb down)

**Comment by LRossman** [comment]
Per @samhatchett 's request, I reverted my earlier commits involving the hash table files and left a comment on his "hash table to map" PR with instructions on how to modify his changes to incorporate my suggestions.

**Comment by samhatchett** [comment]
Great - i think we're good on this PR

**Pull request merged**
