### PR TITLE
uses STL map instead of custom hashtable

### PR DESCRIPTION
**Pull request by samhatchett**
this PR removes the custom `Hashtable` implementation in favor of the STL map class template. it should require no changes to users of the library, but should improve performance. also, it removes some complexity from the code where it needs to keep a dictionary of `Element*`s - we should not be making this complicated when `std::map` works very well for this purpose.

open to feedback or testing/profiling, so I will keep this parked here in the meantime.

### CODE REVIEW

**Comment by LRossman** [comment]
I see two problems with the switch to STL map. First, one is storing a copy of the element name in the map, thus doubling the amount of storage used for ID names. The custom HashTable stores just a pointer to the name which avoids duplication and has faster lookup. Second, because Map uses a (balanced?) tree structure to store the names in sorted fashion it generally performs slower than a hash table does. See http://supercomputingblog.com/windows/ordered-map-vs-unordered-map-a-performance-study/. The custom HashTable could be replaced with the STL unordered_map template which is now part of the C++11 library. However it doesn't include string pointers (as opposed to strings) in its collection of standard key types -- one would have to provide a hash function to it as well as a memory allocator. My preference would be to keep the HashTable for now, but consider it as just an interface whose implementation could change if "offline" testing shows that a different method works better.

**Comment by samhatchett** [comment]
@LRossman : thanks for your thoughts. This PR was intended to demonstrate a minor "internal" change and get some discussion going. So, success! To begin, there are probably a few different ways to define "working better".

I would suggest that one way for a project to work better would be to use as many off-the-shelf components as is practical - and maybe an ordered map is not as performant as an unordered for certain operations, and that may not be as performant as a custom hash table, but I'm thinking about how to make this easy to maintain, understand, and extend.

So of course I can't relate the performance tradeoffs until we run this branch through some evaluations. I can say that the epanet v2-style hash map suffers mightily when I throw a big network at it (Denver = 300K+ nodes) due to hash collisions, and that's tied into the max size of the table (hard coded as 2048 here). Increased memory footprint is probably acceptable tradeoff for faster lookups. STL Map also has the benefit of being easy to inspect from most debuggers.

Worth mentioning, it doesn't really bother me to store the string element name twice - although it does seem curious to store two different indexes for each element (one as an element ivar, and another as the location in the element's containing vector). But that's a level or two up from where we are right now in this discussion :)

It's a world of tradeoffs, right? Why use std::vector, when we could write our own super-performant array implementation? The reason is that the more complexity we can bury and thus not have to maintain, the more time we can spend in higher-level tasks.

**Comment by michaeltryby** [comment]
STL in C++ 11 has an unordered_map why not use that instead of map. That way both of you can be right.

**Comment by jamesuber** [comment]
That seems logical. Though still we will have the underlying philosophical difference that will continue to surface - are we designing fundamentally to enhance understanding and encourage participation and extension? Or is our fundamental goal to produce the most raw efficiency from a high level language implementation. This has got to be one of the most basic issues in all of computer science, and I think that field has pretty much got it sorted out. But we haven't. 

Jim

Jim Uber • 513-368-6303 • www.citilogics.com

**Comment by willfurnass** [comment]
Good points @jamesuber.  Perhaps a simple survey of the community would be useful here: 
1. How important is the performance vs readability/extensibility of EPANET to you on a scale of 1..10; 
2. What would your answer be to 1. if many models could safely be instantiated and run in parallel?

Probably worth moving this discussion to the main mailing list...

**Comment by michaeltryby** [comment]
@willfurnass I respectfully disagree. I don't see the value in opening this up for wider discussion. Open Source works best when the people writing the code get to decide issues like this. If someone thinks they can make the code more clear or perform better they should open their editor, write some code, and make a pull request. 

Getting the same functionality with fewer lines of code is the best kind of refactoring. With this change we are losing 140 lines. It would be informative, however, to know how much memory / performance if any is being sacrificed. 

One thing we could do is measure run time and memory usage when we do regression testing so we can get some extra utility out of our test suite. I am doing that right now on the SWMM side.

**Comment by samhatchett** [comment]
Good thoughts Michael. Can you point us to the performance testing code? Is it in Python?

**Comment by michaeltryby** [comment]
I've been playing around with this Python package: 
https://github.com/davidchall/nrtest

It dumps out runtime and max memory usage when a test is executed. It also shows how Numpy can be used to account for the desired numerical precision when comparing results from different versions. 

I am currently working on custom comparison routines using the Output API.

**Comment by LRossman** [comment]
I did some benchmarking of the different hashing options that have been discussed in this thread. The average times in seconds for loading a project file for four large networks are as follows:

| # Links | HT-1 | Map | U_Map | HT-2 |
| --- | --- | --- | --- | --- |
| 30,602 | 2.56 | 2.40 | 2.59 | 2.33 |
| 37,073 | 3.41 | 3.25 | 3.31 | 3.03 |
| 57,460 | 3.18 | 2.84 | 2.94 | 2.86 |
| 113,173 | 9.84 | 7.12 | 7.11 | 6.64 |

HT-1 is the original custom hash table whose size is fixed at 2,048 buckets, Map is the STL map template, U_Map is the STL unordered map template, and HT-2 is a modified custom hash table. HT-2 sets the size of the node and link tables to the number of each type of element determined after the first of EPANET's two passes through the input file. Note that these times are for processing the entire input file, not just the hashing functions.

The different methods seem to perform about the same for networks below 60,000 pipes in size. For the largest network, HT-2 is significantly faster than HT-1 and slightly faster than both of the STL methods. Unlike the STL methods, HT-2 stores only a pointer to the element's name, not a duplicate copy of the name, and thus uses less memory.

**Comment by samhatchett** [comment]
thanks for the analysis, @LRossman !

This is pretty much why the STL exists. To free up programmers from re-implementing basic functionality. And no generic solution is going to out-perform custom domain-specific code, but it seems like the STL (ordered/unordered)map gives enough advantage in maintainability and code simplicity with reasonable tradeoff. Are we open-source developing this code to optimize for performance alone, or are we also optimizing for each other's development time and for those who may just be joining the effort?

Anyway, I can also confirm similar results on the 300K+ node model, just looking at the loading part. If we wanted to go full-bore, then we should also profile likely usage patterns, like looking up each individual element by name. However that's probably overkill for this type of change since the advantages are pretty clear.

**Comment by michaeltryby** [comment]
@LRossman I appreciate the work that went into this. Based on the trade offs involved, however, when looking at the performance numbers I draw a different conclusion. From my perspective it looks like STL Map is the way to go. We lose 140 lines of code and the performance difference is negligible.

**Comment by michaeltryby** [comment]
One way around the memory issue would be to store the element name as the map key and use a pointer to the key in the element object. Just a thought.

**Comment by samhatchett** [comment]
@michaeltryby that's tricky. but brings up an interesting point about cache invalidation - like what happens if the element name changes after loading? that's not really answered by any solution yet.

**Comment by michaeltryby** [comment]
@samhatchett good point. I think the root of the problem is that two different containers are being used to store and organize the data. If we are going to maintain custom container code I think that is the problem we should address. On the Python side we are contemplating using an IndexedList container [https://gist.github.com/jterrace/895134]. It combines list and dictionary functionality.

**Comment by samhatchett** [comment]
interesting. although I could probably make an argument that it's not the engine's responsibility to keep this old accessor pattern around (looking up an element by name) - it doesn't feel very Object-Oriented™. Maybe the input file parser needs to keep track of names in order to get everything built and connected, but after that point, each element has a name variable as a convenience but it doesn't matter for computation. And maybe your UI code needs to keep track of names in a hashed fashion, but that's up to you to decide. 

not suggesting that we sacrifice the good for the perfect, just throwing it out there for consideration.

**Comment by samhatchett** [comment]
In the absence of an agreed-upon governance model for accepting changes of this sort, I wonder if we can start a 72-hour voting clock, as [suggested here](http://oss-watch.ac.uk/resources/meritocraticgovernancevoting) - I want to say that i'm totally open to feedback and it's important for folks to communicate any opinions they may have. Please use the framework below as a guide to voting & feedback, and note that the outcome of a positive vote will be a merged PR, pending modifications suggested and deemed important or useful. A `-1` vote means that you have a defensible better idea and the ability to implement. 

And unless objections are raised (given the tenor of the discussion above), I figure this should be done as "lazy consensus", which means that "as long as nobody explicitly opposes a proposal or patch, it is recognised as having the support of the community"
- `+1` ‘yes’, ‘agree’: also willing to help bring about the proposed action
- `+0` ‘yes’, ‘agree’: not willing or able to help bring about the proposed action
- `-0` ‘no’, ‘disagree’: but will not oppose the action’s going forward
- `-1` ‘no’, ‘disagree’: opposes the action’s going forward and must propose an alternative action to address the issue (or a justification for not addressing the issue)

**Comment by michaeltryby** [comment]
Good suggestion @samhatchett. Let's say the clock starts when you posted your request for a vote. Where should we vote? On this thread or somewhere else?

**Comment by samhatchett** [comment]
we should vote on where to do the voting. just kidding. 

i'm open to suggestions as always. 

one way is to use the "reaction" emoji on the first post ^^ way up top of the thread so that all results will be aggregated in one place?
- 👍 = +1 (thumb up)
- 😄= +0 (laugh)
- 😕 = -0 (confused)
- 👎 = -1 (thumb down)

... and leave a comment below if necessary. A `-1` requires comment.

**Comment by michaeltryby** [comment]
How many times am I allowed to vote? :smile:

**Comment by samhatchett** [comment]
bummer, you can actually post multiple reactions... well i guess we have to use the honor system.

**Comment by LRossman** [comment]
I'm OK with the proposal

**Comment by michaeltryby** [comment]
Shouldn't be a problem. We are all honorable people here.

**Comment by LRossman** [comment]
I voted OK, How do we handle minor bugs that obviously need fixing (like the one I discovered this morning where the listing of control actions in the Status Report is missing line feeds so they wind up being strung out on a single line)?

Also (off topic) how do I delete a comment once I start typing it and decide I'd rather not post it?

**Comment by samhatchett** [comment]
@LRossman : thanks! I guess minor obvious bugs can be handled without too much fanfare. There's a good orientation to the GitHub Flow here: https://guides.github.com/introduction/flow/ ... I would suggest using a "dev" or "next" branch to carry all the contributions leading up to a release, and use sub-branches from that for fixes. So "master"->"dev"->"fix-status-report". Then merge into dev once the checks have passed. I should say that merging into `master` outside of a release plan is a bit of a faux pas, but here we are.

Since you are a "Collaborator", you can commit and PR within this repository. Non-collaborators like Tom have to fork into their own repo and PR from there.

This should really all go into a README or wiki ...

Should add that Watchers will get notified when things happen here so we will try not to embarrass ourselves or make huge commits without leaving time for input.

**Comment by LRossman** [comment]
I suggest that we keep the HashTable class as an interface and populate it with the STL map instead of the custom hash table. The contents of hashtable.cpp would be 

```

#include "hashtable.h"
using namespace std;

//-----------------------------------------------------------------------------

// Insertion function

void HashTable::insert(string* key, Element* value)
{
    table[*key] = value;
}

//-----------------------------------------------------------------------------

// Count function

size_t HashTable::getCount()
{
    return table.size();
}

//-----------------------------------------------------------------------------

// Retrieval function

Element* HashTable::find(const string& key)
{
    auto it = table.find(key);
    if (it != table.end()) return it->second;
    return nullptr;
}
```

with hashtable.h modified accordingly with no need for a constructor/destructor. You would also have to revert network.cpp back to its original state. Making HashTable an interface provides more flexibility for future changes without having to modify the Network module code.

**Pull request merged**
