### PR TITLE
performance improvement by about 30%

### PR DESCRIPTION
**Pull request by WaterDesk**
1. re-implement Utilities::parseNumber method to deprecate stringstreem operator>>
2. re-implement Utilities::split method to deprecate istrimgstream class
3. re-implement ObjectParser::parseLine method
4. use std::unordered_map instead of std::map for beter performance

Test inp file with about 50000+ nodes

### CODE REVIEW

**Comment by LRossman** [comment]
@WaterDesk while I am OK with your changes 2 - 4, I am concerned with change 1. It seems to only work for floating point numbers and not integers plus I question if it is any faster than using the stringstream approach. Could you run your benchmark again with the original `parseNumber `code restored and compare run times. Another approach that is used in EPANET 2 is the following code which also seems to be very fast:
```
int getfloat(char *s, double *y)
/*
**-----------------------------------------------------------
**  Input:   *s = character string
**  Output:  *y = floating point number
**           returns 1 if conversion successful, 0 if not
**  Purpose: converts string to floating point number
**-----------------------------------------------------------
*/
{
  char *endptr;
  *y = (double)strtod(s, &endptr);
  if (*endptr > 0) return (0);
  return (1);
}
```

**Comment by WaterDesk** [comment]
@LRossman There is a page which shows the comparison result between different methods to convert string to double. This native method is the fastest one. https://tinodidriksen.com/2011/05/cpp-convert-string-to-double-speed/
It is about 19 times faster than strtod in msvc, about 4-6 times faster than strtod in gcc and clang.

The template method `parseNumber` only supports double and float data now, not integers. In the project, all usage of `parseNumber`'s parameter is double. So, not supporting integer is not a problem.

**Comment by LRossman** [comment]
@WaterDesk thanks for the reference. Can you revise the new `parseNumber `method to accept numbers in scientific notation (e.g., 1.23e4) which the current method can do?

**Comment by WaterDesk** [comment]
> @WaterDesk thanks for the reference. Can you revise the new `parseNumber `method to accept numbers in scientific notation (e.g., 1.23e4) which the current method can do?

@LRossman You are right. The new `parseNumber` method doesn't accept numbers in scientific notation. I made the regression and create a new PR to fix it #47

**Pull request merged**
